import { Book } from '../book/book.js';
import { Keys } from '../book/keys.js';

export function makeOkTestBook({
    action = 'test_action',
    asin = 'test_asin',
    authorFirstName = 'test_author_first_name',
    authorLastName = 'test_author_last_name',
    category1 = 'test_cat1',
    category2 = 'test_cat2',
    coverFile = 'test_cover_file',
    coverImageUrl = 'test_cover_image_url',
    description = 'test_description',
    edition = '2',
    id = 'test_id',
    illustratorFirstName = 'test_illustrator_first_name',
    illustratorLastName = 'test_illustrator_last_name',
    isbn = 'test_isbn',
    keyword0 = 'test_keyword0',
    keyword1 = 'test_keyword1',
    keyword2 = 'test_keyword2',
    keyword3 = 'test_keyword3',
    keyword4 = 'test_keyword4',
    keyword5 = 'test_keyword5',
    keyword6 = 'test_keyword6',
    language = 'afrikaans',
    manuscriptCreationCommand = 'test_manuscript_creation_command',
    manuscriptFile = 'test_manuscript_file',
    newCategory1 = 'test_new_cat1',
    newCategory2 = 'test_new_cat2',
    newCategory3 = 'test_new_cat3',
    notes = 'test_notes',
    paperBleed = 'no',
    paperColor = 'premium-color',
    paperCoverFinish = 'glossy',
    paperTrim = '6x9',
    priceAu = '1.1',
    priceCa = '2.1',
    priceEur = '3.1',
    priceGbp = '4.1',
    priceJp = '5.1',
    pricePl = '6.1',
    priceSe = '7.1',
    priceUsd = '8.1',
    primaryMarketplace = 'pl',
    pubDate = 'test_pub_date',
    pubStatus = 'test_pub_status',
    pubStatusDetail = 'test_pub_status_detail',
    publishTime = '2011-10-05T21:48:00.000Z',
    scrapedSeriesTitle = 'test_scraped_series_title',
    scrapedIsArchived = 'archived',
    seriesTitle = 'test_series_title',
    signature = 'test_signature',
    subtitle = 'test_subtitle',
    title = 'test_title',
    titleId = 'test_title_id',
    wasEverPublished = 'false',
} = {}) {
    return new Book(
        makeMap(
            Keys.ACTION, action,
            Keys.ASIN, asin,
            Keys.AUTHOR_FIRST_NAME, authorFirstName,
            Keys.AUTHOR_LAST_NAME, authorLastName,
            Keys.CATEGORY1, category1,
            Keys.CATEGORY2, category2,
            Keys.NEW_CATEGORY1, newCategory1,
            Keys.NEW_CATEGORY2, newCategory2,
            Keys.NEW_CATEGORY3, newCategory3,
            Keys.COVER_FILE, coverFile,
            Keys.COVER_IMAGE_URL, coverImageUrl,
            Keys.DESCRIPTION, description,
            Keys.ID, id,
            Keys.TITLE_ID, titleId,
            Keys.ILLUSTRATOR_FIRST_NAME, illustratorFirstName,
            Keys.ILLUSTRATOR_LAST_NAME, illustratorLastName,
            Keys.ISBN, isbn,
            Keys.KEYWORD0, keyword0,
            Keys.KEYWORD1, keyword1,
            Keys.KEYWORD2, keyword2,
            Keys.KEYWORD3, keyword3,
            Keys.KEYWORD4, keyword4,
            Keys.KEYWORD5, keyword5,
            Keys.KEYWORD6, keyword6,
            Keys.LANGUAGE, language,
            Keys.MANUSCRIPT_CREATION_COMMAND, manuscriptCreationCommand,
            Keys.MANUSCRIPT_FILE, manuscriptFile,
            Keys.NOTES, notes,
            Keys.PAPER_BLEED, paperBleed,
            Keys.PAPER_COLOR, paperColor,
            Keys.PAPER_COVER_FINISH, paperCoverFinish,
            Keys.PAPER_TRIM, paperTrim,
            Keys.PRICE_AU, priceAu,
            Keys.PRICE_CA, priceCa,
            Keys.PRICE_EUR, priceEur,
            Keys.PRICE_GBP, priceGbp,
            Keys.PRICE_JP, priceJp,
            Keys.PRICE_PL, pricePl,
            Keys.PRICE_SE, priceSe,
            Keys.PRICE_USD, priceUsd,
            Keys.PRIMARY_MARKETPLACE, primaryMarketplace,
            Keys.PUB_DATE, pubDate,
            Keys.PUB_STATUS, pubStatus,
            Keys.PUB_STATUS_DETAIL, pubStatusDetail,
            Keys.PUBLISH_TIME, publishTime,
            Keys.SIGNATURE, signature,
            Keys.SUBTITLE, subtitle,
            Keys.EDITION, edition,
            Keys.TITLE, title,
            Keys.SERIES_TITLE, seriesTitle,
            Keys.SCRAPED_SERIES_TITLE, scrapedSeriesTitle,
            Keys.SCRAPED_IS_ARCHIVED, scrapedIsArchived,
            Keys.WAS_EVER_PUBLISHED, wasEverPublished,
        ),
        makeMap(),
        'content/dir',
        []);
}

export function makeMap(...vals: string[]): Map<string, string> {
    let m = new Map();
    for (let i = 0; i + 1 < vals.length; i += 2) {
        m.set(vals[i], vals[i + 1]);
    }
    return m;

}
